08-ASP.NET CORE MVC/04-view/ViewDemo/ViewDemo/Models/ErrorViewModel.cs
namespace ViewDemo.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

08-ASP.NET CORE MVC/04-view/ViewDemo/ViewDemo/Models/Produit.cs
namespace ViewDemo.Models
{
    public class Produit
    {
        public int Id { get; set; }
        public string Nom { get; set; }
        public decimal Prix { get; set; }
        public int Stock { get; set; }
    }
}

08-ASP.NET CORE MVC/04-view/ViewDemo/ViewDemo/Models/Utilisateur.cs
namespace ViewDemo.Models
{
    public class Utilisateur
    {
        public string Nom {  get; set; }
        public string CodePays { get; set; }
    }
}

08-ASP.NET CORE MVC/04-view/ViewDemo/ViewDemo/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using ViewDemo.Models;

namespace ViewDemo.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            var message = 10;
            return View((object)message);
        }

        public IActionResult ifElse()
        {
            return View();
        }

        public IActionResult Foreach()
        {
            return View();
        }

        public IActionResult AvecModelSimple()
        {
            return View();
        }


        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

08-ASP.NET CORE MVC/04-view/ViewDemo/ViewDemo/Controllers/ProduitController.cs
using Microsoft.AspNetCore.Mvc;
using ViewDemo.Models;

namespace ViewDemo.Controllers
{
    public class ProduitController : Controller
    {
        public IActionResult Index()
        {
            ViewData["Title"] = "Nos Produits";
            //var produit = new Produit()
            //{
            //    Id = 1,
            //    Nom = "Ordinateur",
            //    Prix = 1299.99m,
            //    Stock = 0
            //};
            var produits = new List<Produit>
            {
                new Produit
                {
                    Id=1,
                    Nom = "Ordinateur",
                    Prix = 500.25m,
                    Stock = 10
                },
                new Produit
                {
                    Id=2,
                    Nom = "Clavier",
                    Prix = 15.25m,
                    Stock = 5
                },
                new Produit
                {
                    Id=3,
                    Nom = "Souris",
                    Prix = 25.25m,
                    Stock = 50
                }
            };

            return View(produits);
        }

        public IActionResult Details() 
        {
            return Content("Page de détails");

        }

        public IActionResult DetailsAvecParametre(int id)
        {
            return Content($"Page de détails du produit {id}");

        }

        public IActionResult Liste(string categorie, string sort)
        {
            return Content($"Page liste produits electroniques");

        }
    }
}

08-ASP.NET CORE MVC/04-view/ViewDemo/ViewDemo/Controllers/ProduitFormulaireController.cs
using Microsoft.AspNetCore.Mvc;
using ViewDemo.Models;

namespace ViewDemo.Controllers
{
    public class ProduitFormulaireController : Controller
    {
        private static List<Produit> _produits = new List<Produit>();

        private static int _nextID = 1;
        public IActionResult Index()
        {
            return View(_produits);
        }

        [HttpGet] //affiche le formulaire vide
        public IActionResult CreerProduit()
        {
            return View(new Produit()); //crée un produit vide pour le formulaire
        }

        [HttpPost]
        public IActionResult CreerProduit(Produit produitCree)
        {
            produitCree.Id = _nextID;
            _nextID++;

            _produits.Add(produitCree);

            return RedirectToAction("Index");
        }

        public IActionResult Details(int id)
        {
            var produit = _produits.FirstOrDefault(i=>i.Id == id);

            return View(produit);
        }
    }
}

08-ASP.NET CORE MVC/04-view/ViewDemo/ViewDemo/Controllers/UtilisateurController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ViewDemo.Models;

namespace ViewDemo.Controllers
{
    public class UtilisateurController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        // Affiche le formulaire vide avec la liste des pays
        [HttpGet]
        public IActionResult CreerUnUtilisateur()
        {

            ViewBag.pays = new List<SelectListItem>()
            {
                new SelectListItem{ Value = "FR", Text = "France" },
                new SelectListItem{ Value = "BE", Text = "Belgique" },
                new SelectListItem{ Value = "CA", Text = "Canada" },

            };

            return View(new Utilisateur());
        }
    }
}

08-ASP.NET CORE MVC/04-view/ViewDemo/ViewDemo/Views/Home/AvecModelSimple.cshtml
@{
}

08-ASP.NET CORE MVC/04-view/ViewDemo/ViewDemo/Views/Home/Foreach.cshtml
@{
    var produits = new[] { "Ordinateur", "Clavier", "Souris", "Ecran" };
}

<h2>Liste des produits</h2>

<ul>
    @foreach(var produit in produits)
    {
        <li>@produit</li>
    }
    
</ul>

08-ASP.NET CORE MVC/04-view/ViewDemo/ViewDemo/Views/Home/Index.cshtml
@model int

@{
    ViewData["Title"] = "Home Page";

    var message = "Bonjour depuis Razor";
    int nombre = 42;

    var nom = "Moi";
    var prenom = "Oussama";

    var fullname = $"{nom} {prenom}";

    var produits = new List<string> { "Ordinateur", "Clavier", "Souris" };
    var total = 1200.25m; // informe que c'est un decimal
}

<h1>@ViewData["Title"]</h1>
<p>@message</p> <p>@Model</p>
<p>Le nombre est : @nombre</p>
<p>Le double de ce nombre est : @(nombre * 2)</p>

<hr />

<h2>Bienvenue @fullname</h2>
<p>Vous avez @produits.Count produit(s) dans votre panier</p>
<p>Total : @total.ToString("C")</p>

08-ASP.NET CORE MVC/04-view/ViewDemo/ViewDemo/Views/Home/ifElse.cshtml
@{
    ViewData["Title"] = "La page IF ELSE";

    var isConnecte = false;
    var stock = 0;
}

@if (isConnecte)
{
    <p>Bienvenue, Vous êtes connecté !</p> // ne s'affiche que si la condition est vrai'
}

@if(stock > 0)
{
    <span class="badge bg-success">En stock</span>
}
else
{
    <span class="badge bg-danger">Rupture de stock</span>

}

08-ASP.NET CORE MVC/04-view/ViewDemo/ViewDemo/Views/Produit/Index.cshtml
@* @model Produit
@{
}
<h1>@ViewData["Title"]</h1>

<h2>@Model.Nom</h2>
<p>Prix : @Model.Prix.ToString("C")</p>
<p>Disponible : @(Model.Stock > 0 ? "Oui" : "Non")</p> *@

@model List<Produit>

<h1>@ViewData["Title"]</h1>

<h2>@Model.Count produit(s)</h2>

<table class="table">
    <thead class="table-dark">
        <tr>
            <th>Id</th>
            <th>Nom</th>
            <th>Prix</th>
            <th>stock</th>
        </tr>
    </thead>
    <tbody>
    @foreach(var produit in Model)
    {
        <tr> 
            <td>@produit.Id</td>
            <td>@produit.Nom</td>
            <td>@produit.Prix.ToString("C")</td>
            <td>@produit.Stock</td>
        </tr>
    }
    </tbody>
    
</table>

<hr />

@*Lien simple vers une action*@
<a asp-controller="Produit" asp-action="Details" class="btn btn-primary" >Voir Details d'un produit</a>

@*Liens avec des paramètres de route*@
<a asp-controller="Produit" asp-action="Details" asp-route-id="5" class="btn btn-info">Voir le produit #5</a>

@*Lien avec plusieurs paramètres*@
<a asp-controller="Produit" asp-action="Liste" asp-route-categorie="Electronique" asp-route-sort="prix" class="btn btn-info">Produits electroniques</a>